image: registry.mokahr.com/ops/base:docker

stages:
  - build
  - deploy

before_script:
  ##设置部门
  - DEP=ai
  ##替换 branch 特殊字符
  - CI_COMMIT_REF_SLUG=`echo  ${CI_COMMIT_REF_SLUG//\//\-}`
  ##- TIME=`date +%Y%m%d-%H%M`
  - CITIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
  - TIME=$(date -d @${CITIME}  "+%Y%m%d-%H%M")
  ##设置镜像地址
  - IMAGE_VERSION=${TIME}-${CI_COMMIT_SHA:0:5}-${CI_COMMIT_REF_SLUG}
  - ALI_IMAGE_URL=${ALI_REGISTRY}/${DEP}/${CI_PROJECT_NAME}:${IMAGE_VERSION}
  - TC_IMAGE_URL=${TC_REGISTRY}/${DEP}/${CI_PROJECT_NAME}:${IMAGE_VERSION}

  
Build Image:
  stage: build
  image: registry.mokahr.com/ops/base:docker
  script:
    #初始化运维环境
    - sh /entrypoint.sh
    ##构建镜像
    - docker build -t ${ALI_IMAGE_URL} -t ${TC_IMAGE_URL} -f ops/Dockerfile .
    ##推送镜像
    - docker push ${ALI_IMAGE_URL}
    - docker push ${TC_IMAGE_URL}
    - echo -e "本次构建镜像版本:\n${IMAGE_VERSION}\n本次构建镜像地址\n阿里云:${ALI_IMAGE_URL}\n腾讯云:${TC_IMAGE_URL}"
    - sh /ci-end.sh build_image ${GITLAB_USER_NAME} ${DEP} ${CI_PROJECT_NAME} ${IMAGE_VERSION} ${CI_COMMIT_TAG}

Deploy Staging:
  stage: deploy
  image: registry.mokahr.com/ops/base:docker
  script:
    - NAMESAPCE=`echo ${CI_COMMIT_TAG}|cut -d '-' -f1-2`
    - Dep=`echo ${DEP}| tr 'a-z' 'A-Z'`
    # - /jenkins-tools  -j Staging-Java-${Dep}-${CI_PROJECT_NAME} -n ${NAMESAPCE} -a ${CI_PROJECT_NAME} -v ${IMAGE_VERSION}
    # - echo -e "本次发布信息\nJob:Staging-Java-${Dep}-${CI_PROJECT_NAME}\n环境:${NAMESAPCE}\n镜像版本:${IMAGE_VERSION}"
    # - sh /ci-end.sh deployment ${GITLAB_USER_NAME} ${DEP} ${CI_PROJECT_NAME} ${IMAGE_VERSION} ${CI_COMMIT_TAG}
  only:
      - tags
